project:
  type: book
  output-dir: docs
book:
  title: "CASA0023 Remotely Sensing Cities and Environments Learning Diary"
  author: "Jiaying Li"
  date: "2/1/2026"
  chapters:
    - index.qmd
    - intro.qmd
    - portfolio.qmd
    - corrections.qmd
    - policy.qmd
    - gee.qmd
    - classification_i.qmd
    - classification_ii.qmd
    - temperature.qmd
    - sar.qmd
    - resources.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: 
      -cosmo
      - brand
  pdf:
    documentclass: scrreprt

editor: visual

