project:
  type: book
  output-dir: docs
book:
  title: "Jiaying-2026 portfolio"
  author: "Norah Jones"
  date: "3/7/2026"
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

